"""empty message

Revision ID: 04da60b75486
Revises: 
Create Date: 2025-03-27 18:47:21.742304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04da60b75486'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('game_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'link'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'link'"))
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
